project:
  type: website

website:
  title: "<span style='color:#E41B17;font-weight:bold'>AMOR/e</span>"
  favicon: images/favicon.ico 
  navbar:
    logo: "images/logo2.png"
    collapse-below: lg
    left:
      - index.qmd
      - projects/projects.qmd
      - publications/publications.qmd
      - software/software.qmd
      - blogs/blog.qmd
      - people/people.qmd
      - join/join.qmd
    right:
      - icon: github
        href: https://github.com/amore-labs

format:
  html:
    theme: [cosmo, styles.scss]
    respect-user-color-scheme: true
    css: styles.css
    toc: true
